version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      CLIENT: postgresql
      DATABASE: hospital
      DB_USER: postgres
      DB_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      bash -c "
      until psql -h localhost -U postgres -c '\q'; do
        echo 'Postgres is unavailable - sleeping';
        sleep 1;
      done;
      psql -h localhost -U postgres -c 'CREATE DATABASE IF NOT EXISTS mydatabase';
      "

  mysql:
    image: mysql
    environment:
      CLIENT: sqlite3
      DATABASE: hospital
      DB_USER: root
      DB_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  haproxy:
    image: haproxy
    ports:
      - "8404:8404"
      - "8080:8080"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

volumes:
  postgres_data:
  mysql_data:
