version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "3002:5432"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3308:3306"


  redis:
    image: redis:latest
    ports:
      - "6380:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15773:15672"

  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  haproxy:
    image: haproxy:latest
    ports:
      - "8404:8404"
      - "8080:8080"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

volumes:
  postgres_data:
  mysql_data:
