# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "PORT=5000" >> .env
          echo "# Postgres" >> .env
          echo "POSTGRES_HOST=127.0.0.1" >> .env
          echo "POSTGRES_USER=postgres" >> .env
          echo "POSTGRES_PASSWORD=1234" >> .env
          echo "POSTGRES_DB=hospital" >> .env
          echo "# mysql" >> .env
          echo "MYSQL_HOST=localhost" >> .env
          echo "MYSQL_ROOT_PASSWORD=12345" >> .env
          echo "MYSQL_DATABASE=adminpanel" >> .env
          echo "MYSQL_USER=root" >> .env
          echo "MYSQL_PASSWORD=" >> .env
          echo "TOKEN_SECRET=secret" >> .env

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm run build --if-present
      # - run: docker compose down
      # - run: docker compose up -d
      - run: pm2 restart 3
